Add refund if amount is lower than fee amount
threefoldfoundation/tft pull request #37
Opened 2021-05-03 10:04 UTC by DylanVerstraete

2021-05-03 10:05 UTC, DylanVerstraete commented
An edge case here is that a refund might fail due to one or more peers are disconnected. It's better we follow this up in another pr

2021-05-03 16:37 UTC, LeeSmet requested changes

2021-05-03 16:37 UTC, LeeSmet commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +				// }
why is this check commented? it seems necessary, and also, should be refined to make sure the payed amount is equal to the deposited amount (minus the 0.1 TFT tx fee I suppose)

2021-05-03 16:37 UTC, LeeSmet commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +		// }
commented code should be removed

2021-05-04 04:56 UTC, robvanmieghem requested changes
Use the  memo type MEMO_RETURN with the sending receivingtransaction hash as memo.
This type is meant for that and this way we can easily track which refunds already happened and provide proof if needed.

2021-05-18 12:43 UTC, robvanmieghem requested changes

2021-05-18 12:43 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/bridge.go
> +	DepositFee    = 500000000
Please add the comment here:  // 50 TFT with a precision of 7decimals

2021-05-18 12:43 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/signer.go
>  			case <-ctxWithTimeout.Done():
I was looking at the sign implementation where the context is passed to, why do we need a select case here?

The context will interrupt the call to sign anyway so just writing to the response to the buffered channel will do the trick

2021-05-18 12:43 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
???

2021-05-18 13:28 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/signer.go
>  			case <-ctxWithTimeout.Done():
Not relavant here, I removed code that was leftover from a different time

2021-05-18 13:48 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
If you don't return here, you will be stuck in an infinite loop?

2021-05-19 04:07 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/stellar.go
> -	// Only try to request signatures if there are signatures required
Why is this check removed?

2021-05-19 04:16 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
Off course you need to keep retrying, the refund  will never happen again if you don't and and if  a following mint or refund succeeds, even restarting the master of the bridge will not solve it.

2021-05-19 06:23 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
A refund can error if it already happened before. The signers do some checks before refunding and return an error if there is a double refund for example. In that case the bridge will be stuck here ..

2021-05-19 06:26 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/stellar.go
> -	// Only try to request signatures if there are signatures required
I think it's removed due some rebasing, I will revert

2021-05-19 06:50 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
Off course but the master should also check if the refund already happened in which case there is no error since no signing needs to happen. And a submit to Stellar can and will fail sometimes (Timeout for example). Also if not enough signatures can be collected in time it should be retried.

2021-05-19 06:52 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/stellar.go
> +						return
If the master needs to check if a refund already happened alot more stuff needs to be accounted for in the master bridge. We already have this working on the signer side, no need to duplicate code no?

2021-05-27 14:35 UTC, LeeSmet approved these changes
LGTM codewise

2021-05-28 08:10 UTC, robvanmieghem approved these changes
LGTM

2021-05-28 08:10 UTC, merged