Implement fee wallet
threefoldfoundation/tft pull request #49
Opened 2021-05-04 14:41 UTC by DylanVerstraete

2021-05-28 08:11 UTC, robvanmieghem commented
@DylanVerstraete Can you resolve the conflicts?

2021-05-28 08:14 UTC, DylanVerstraete commented
> @DylanVerstraete Can you resolve the conflicts?

Yes! :-)

2021-05-28 09:01 UTC, robvanmieghem requested changes
Shouldn't  the withdraw fee be substracted  from the amount? and if the amount is less than the withdraw fee, nothing needs to be done or maybe transfer the amount to the feewallet, if not the amount on bsc is not in sync with the amount on the bridgewallet.

2021-06-01 15:28 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/bridge.go
> +	amount -= uint64(WithdrawFee)
What if amount is less than the withdraw fee? I am seeing that this is happening on testnet now. The contract does not forbid the user to withdraw less than 1 TFT. If the amount if lower than the withdraw fee we should transfer this amount to the fee wallet and return

2021-06-02 06:53 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/bridge.go
> +	amount -= uint64(WithdrawFee)
I still had to handle that case

2021-06-02 06:54 UTC, DylanVerstraete commented on bsc/bridges/stellar/api/bridge/bridge.go
> +	amount -= uint64(WithdrawFee)
I am currently working on it, will push a solution

2021-06-04 07:05 UTC, merged