add replay protection for withdraw transactions
threefoldfoundation/tft pull request #74
Opened 2021-05-11 11:58 UTC by DylanVerstraete

2021-05-11 14:16 UTC, LeeSmet requested changes
While the logic is technically correct, I feel that there will (quickly) be issues in the form of the horizon rate limiting. More specifically, the cursor is not persisted across calls. While this is correct, as there is no way of knowing if all txes have already been scanned, it also means that for valid withdrawals, all txes of the account will be loaded, every time. If there are a lot of txes happening, this will do a lot of calls, which in turn will cause multiple horizon requests. If there is then a period of a lot of withdrawals, these requests can break the bridge by triggering horizons rate limiting.

A better solution imo, would be to do a full scan when the bridge starts, oldest to newest, and memorizing the cursor afterwards (which is then at the latest transaction). A valid transaction would then only cause a single horizon request, instead of going through all txes of the address, as is the case now. Also, memos which have already been used will then, necessarily, already be in the memo cache, and not require a horizon request, making a "double withdraw attempt" trivially cheap to detect

2021-05-18 04:35 UTC, robvanmieghem requested changes
Looks good, just a few small changes

2021-05-18 04:35 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +	brideMasterAddress    string
bridge, not bride

2021-05-18 04:35 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +		log.Info("Error getting transactions for stellar account", "error", err)
this can always happen ( horizon or network problem), sleep a while and retry

2021-05-18 04:35 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +		if len(response.Embedded.Records) < stellarPageLimit {
your stellar paging limit is 200, If I'm not mistaken, the max limit is 100

2021-05-18 04:35 UTC, robvanmieghem commented on bsc/bridges/stellar/api/bridge/signer_server.go
> +	for len(response.Embedded.Records) != 0 {
rework this loop a bit like the in fetchtransactions,

2021-05-18 08:08 UTC, merged